platform:ios, '13.0'

# github 官方 pod 源
source 'https://github.com/CocoaPods/Specs.git' 

# 阿里云 pod 源
source 'https://github.com/aliyun/aliyun-specs.git' 

use_frameworks!

def openSource
  
  pod 'Starscream', '4.0.8'
  pod 'PinLayout', '1.10.4'
  pod 'SDWebImage', '5.21.0'
  pod 'MJRefresh', '3.1.15'
  pod 'ZipArchive', '1.4.0'
  pod 'CryptoSwift', '1.8.3'

end

target "MXApp" do

  openSource
    
  pod 'lottie-ios', '4.4.1'
  
  pod 'MeshSDK', :path => '../'
  pod 'dsBridge', :path => '../'
  pod 'MXURLRouter', :path => '../'
  pod 'MXAPIManager', :path => '../'
  pod 'MXFogProvision', :path => '../'

end


pre_install do |installer|
  Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
end

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
            # 添加架构设置
            config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
            config.build_settings['ONLY_ACTIVE_ARCH'] = 'YES'
            # 确保正确的链接设置
            config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
            config.build_settings['SWIFT_COMPILATION_MODE'] = 'wholemodule'
            config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-O'
         end
    end
  end
end
